from pydantic import BaseModel
from typing import List, Optional
from enum import Enum

class CampaignPhase(str, Enum):
    DISCOVERY = "discovery"
    PLANNING = "planning"
    EXECUTION = "execution"
    ANALYSIS = "analysis"

class ContentPiece(BaseModel):
    """A single piece of content to be produced"""
    id: str
    title: str
    description: str
    channels: List[str]
    phase: CampaignPhase
    messaging_hierarchy: Optional[List[str]] = None
    key_points: List[str]

class CampaignPlan(BaseModel):
    """Complete campaign plan generated by architect"""
    campaign_name: str
    overview: str
    phases: List[dict]
    content_pieces: List[ContentPiece]
    messaging_strategy: str
    timeline: dict
    success_criteria: List[str]
